version: "3.8"
services:
  client:
    image: autokg-client
    build: ./client/
    stdin_open: true
    ports:
      - "3020:3000"
    networks:
      - autokg-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
  server:
    image: autokg-server
    build: ./server/
    stdin_open: true
    ports:
      - "3010:3010"
    networks:
      - autokg-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.8
    ports:
      - "27018:27017"
    networks:
      - autokg-app
    volumes:
      - mongo-data:/data/db
    depends_on:
      - server_cluster
  server_cluster:
    image: autokg-server-cluster
    build: ./server_cluster
    stdin_open: true
    ports:
      - "8000:8000"
    networks:
      - autokg-app

networks:
  autokg-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local